source "http://rubygems.org"

gem "jruby-rack"
gem "erubis"
gem "harbor", git: "git://github.com/sam/harbor.git"
gem "rest-client"
gem "json"
gem "bcrypt-ruby"
gem "uuid"
gem "RedCloth"
gem "chronic"
gem "stringex"
