source "http://rubygems.org"

gem "jruby-rack"
gem "erubis"
gem "harbor", git: "git://github.com/sam/harbor.git"
gem "couchrest"
gem "json-jruby"
gem "bcrypt-ruby"
gem "RedCloth"
gem "chronic"
gem "stringex"
gem "ffaker"
gem "minitest"
gem "minitest-wscolor"
gem "rjack-logback"
gem "listen"